'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Radar, ChartNoAxesCombined, ShieldCheck, Cloud, Coins, Menu, X, Wallet, Activity, Bell, Brain, Ghost } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { SearchSheet, type CashperPanel } from '@/components/cashper/search-sheet';
import { SolanaMark } from '@/components/cashper/solana-mark';
const tools = [
 { title:'MONITOR', icon:Radar, tag:'Eyes on the chain', description:'Track wallets, tokens, and important onchain activity.' },
 { title:'ANALYZE', icon:ChartNoAxesCombined, tag:'Less noise. More clarity.', description:'Turn blockchain activity into simple, readable insights.' },
 { title:'PROTECT', icon:ShieldCheck, tag:'A little extra awareness', description:'Spot unusual activity and understand wallet interactions before taking action.' }
];
function Mascot({ className = '', decorative = false }: { className?: string; decorative?: boolean }) { return <img src="/cashper.png" width="1280" height="1280" className={`mascot ${className}`} alt={decorative ? '' : 'Cashper, a friendly white ghost carrying a golden money bag'} />; }
function Solana() { return <span className="solana"><SolanaMark />Built on <strong>Solana.</strong></span>; }
function SignalChart() { return <svg className="signal-chart" viewBox="0 0 424 112" preserveAspectRatio="none" role="img" aria-label="Illustrative on-chain activity signal"><title>Illustrative on-chain activity signal</title><defs><linearGradient id="signal-fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#9aa7ba" stopOpacity=".15"/><stop offset="1" stopColor="#9aa7ba" stopOpacity="0"/></linearGradient></defs><path d="M8 30H416M8 84H416" fill="none" stroke="#eef2f7" strokeWidth="1.5" strokeLinecap="round" strokeDasharray="2 8" vectorEffect="non-scaling-stroke"/><path d="M8 86H58L82 62 106 94 134 34 162 80H192L220 54 248 72H278L306 26 334 90 362 56H404V112H8Z" fill="url(#signal-fade)"/><path d="M8 86H58L82 62 106 94 134 34 162 80H192L220 54 248 72H278L306 26 334 90 362 56H404" fill="none" stroke="#9aa7ba" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"/><path d="M404 56h.01" fill="none" stroke="#9aa7ba" strokeWidth="8" strokeLinecap="round" opacity=".4" vectorEffect="non-scaling-stroke"><animate attributeName="strokeWidth" values="8;24" dur="2.2s" repeatCount="indefinite"/><animate attributeName="opacity" values=".4;0" dur="2.2s" repeatCount="indefinite"/></path><path d="M404 56h.01" fill="none" stroke="#9aa7ba" strokeWidth="7" strokeLinecap="round" vectorEffect="non-scaling-stroke"><animate attributeName="strokeWidth" values="7;5;7" dur="2.2s" repeatCount="indefinite"/></path></svg>; }
export default function Home() {
 const [menu, setMenu] = useState(false);
 const [notice, setNotice] = useState<string | null>(null);
 const [panel, setPanel] = useState<CashperPanel>(null);
 const launch = () => { window.location.assign('/dashboard'); };
 return <><a className="skip" href="#main">Skip to content</a><div className="site-shell">
 <header className="header"><a href="#" aria-label="Cashper home" className="wordmark"><Ghost size={29} strokeWidth={2.5} />CASHPER</a>
 <nav className={menu ? 'nav open' : 'nav'} aria-label="Main navigation">{[['About','about'],['Ghost Tools','tools'],['How It Works','how-it-works'],['Ecosystem','ecosystem']].map(([text,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{text}</a>)}</nav>
 <div className="header-actions"><button className="button nav-launch" onClick={launch}>Launch App <ArrowUpRight size={17} /></button><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu}>{menu?<X />:<Menu />}</button></div></header>
 <main id="main"><section className="hero" id="about"><div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✳</span>A LITTLE SPIRIT. A LOT OF SIGNAL.</div>
 <h1>Your friendly<br />ghost for the<br /><span>onchain world.</span></h1><p>Cashper watches, analyzes, and helps you<br className="desktop-break" /> navigate activity across Solana.</p>
 <div className="hero-actions"><button className="button cream" onClick={launch}>Launch Cashper <ArrowUpRight size={20} /></button><a className="button outline" href="#tools">Explore Ghost Tools <ArrowRight size={18} /></a></div><Solana /></div>
 <div className="hero-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><Cloud className="cloud cloud-one" strokeWidth={1} aria-hidden="true" /><Cloud className="cloud cloud-two" strokeWidth={1} aria-hidden="true" /><Coins className="coin coin-one" aria-hidden="true" /><Coins className="coin coin-two" aria-hidden="true" /><span className="art-star star-one" aria-hidden="true">✦</span><span className="art-star star-two" aria-hidden="true">✦</span><Mascot className="hero-mascot" /><span className="floating-label"><span className="status-dot" />Your onchain companion</span><span className="art-dot dot-one" /><span className="art-dot dot-two" /></div>
 <div className="hero-bottom"><span>GOOD SPIRIT. SHARP INSTINCTS.</span><a href="#tools" aria-label="Scroll to Ghost Tools">↓</a><span>SOLANA, WITH A SIXTH SENSE.</span></div></section>
 <section className="tools-section section" id="tools"><div className="section-top"><div><span className="eyebrow">YOUR ONCHAIN TOOLKIT</span><h2>Meet Your Ghost Tools<span className="cream-dot">.</span></h2></div><p>A friendly face.<br />A sharper view of the chain.</p></div>
 <div className="tool-grid">{tools.map(({title,icon:Icon,tag,description},i)=><button type="button" onClick={()=>setPanel(title === 'PROTECT' ? 'protect' : title.toLowerCase() as CashperPanel)} className={`tool-card tool-${i}`} key={title}><div className="card-top"><span className="tool-icon"><Icon size={32} strokeWidth={1.6} /></span><span className="card-number">0{i+1}</span></div><h3>{title}</h3><p>{description}</p><div className="card-bottom"><span>{tag}</span><ArrowUpRight size={20} /></div></button>)}</div></section>
  <section className="how-section section" id="how-it-works"><div className="center-heading"><span className="eyebrow">THREE STEPS. ONE FRIENDLY GHOST.</span><h2>How It Works<span className="cream-dot">.</span></h2><p>The planned Cashper experience, from connection to clarity.</p></div>
  <div className="steps">{[{title:'Connect',copy:'Connect a Solana wallet.',icon:Wallet},{title:'Deploy Your Ghost',copy:'Choose what Cashper should monitor.',icon:Ghost},{title:'Stay Informed',copy:'Receive useful signals and insights from onchain activity.',icon:Bell}].map(({title,copy,icon:Icon},i)=><article className="step" key={title}><div className="step-visual"><span className="step-icon"><Icon size={27} strokeWidth={1.6}/></span>{i<2&&<div className="step-trail"><span/><Mascot decorative /><span/></div>}</div><span className="step-number">STEP 0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="dashboard-section section" id="dashboard"><div className="dashboard-copy"><span className="eyebrow">A GLIMPSE INSIDE</span><h2>Your ghost.<br /> Your eyes on<br /> the chain<span className="cream-dot">.</span></h2><p>A clear view of the activity that matters to you. All in one calm little corner of the onchain world.</p><span className="preview-note"><span/>Dashboard preview · Sample data</span></div>
  <div className="dashboard"><div className="dashboard-header"><span className="dashboard-brand"><Ghost size={20}/>CASHPER <span>/</span> MY GHOST</span><span className="demo-label">PREVIEW</span></div><div className="dashboard-body"><div className="ghost-summary"><div className="ghost-avatar"><Mascot decorative /></div><div><h3>MY GHOST</h3><span className="ghost-subtitle">Your quiet onchain companion</span></div><span className="active"><span className="status-dot"/>ACTIVE</span></div>
  <div className="watching"><div><span><Wallet size={15}/> WATCHING</span><strong>3 <small>Wallets</small></strong></div><div><span><Coins size={15}/> WATCHING</span><strong>2 <small>Tokens</small></strong></div><div className="signal"><span><Activity size={15}/> ACTIVITY SIGNAL</span><SignalChart/></div></div>
  <div className="activity-heading"><h4>Recent Activity</h4><span>EXAMPLE FEED</span></div><ul className="activity-feed">{[{icon:ArrowUpRight,text:'Wallet movement detected',type:'Wallet activity',time:'2m ago'},{icon:ChartNoAxesCombined,text:'Token liquidity changed',type:'Token activity',time:'12m ago'},{icon:Wallet,text:'New wallet interaction',type:'Wallet activity',time:'24m ago'}].map(({icon:Icon,text,type,time})=><li key={text}><span className="feed-icon"><Icon size={17}/></span><div><strong>{text}</strong><span>{type}</span></div><time>{time}</time></li>)}</ul><div className="dashboard-footer"><span className="status-dot"/>Always curious. Always watching.<Ghost size={17}/></div></div></div></section>
  <section className="brand-section"><div className="brand-art"><span className="brand-orbit"/><Mascot decorative/><span className="art-star">✦</span></div><div><span className="eyebrow">REST EASY. STAY CURIOUS.</span><h2>Ghosts never sleep.</h2><p>Cashper keeps an eye on the chain<br className="desktop-break"/> while you focus on what matters.</p></div><span className="brand-spark" aria-hidden="true">✳</span></section>
 <section className="ecosystem-section section" id="ecosystem"><div className="section-top"><div><span className="eyebrow">THE GHOST ECOSYSTEM</span><h2>A little spirit. More possibilities<span className="cream-dot">.</span></h2></div></div><p className="ecosystem-intro">Future Ghost modules. Thoughtfully taking shape.</p><div className="module-grid">{[{title:'Wallet Watcher',icon:Wallet},{title:'Token Monitor',icon:Coins},{title:'Activity Alerts',icon:Bell},{title:'Ghost Intelligence',icon:Brain}].map(({title,icon:Icon})=><button type="button" onClick={()=>setPanel('ecosystem')} className="module-card" key={title}><Icon size={27} strokeWidth={1.5}/><h3>{title}</h3><span>Coming Soon</span></button>)}</div><p className="roadmap-note">Modules are in development. Availability and features may change.</p></section>
 <footer className="footer"><div className="footer-main"><div><a href="#" className="wordmark"><Ghost size={29} strokeWidth={2.5}/>CASHPER</a><p>Your friendly ghost for the onchain world.</p></div><div className="footer-right"><div className="footer-links">{['X / Twitter','Telegram','Docs'].map(link=><button key={link} onClick={()=>setNotice(`${link} is coming soon.`)}>{link}<ArrowUpRight size={15}/></button>)}</div><span className="contract">CA: <strong>Coming Soon</strong><span className="contract-dot"/></span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} CASHPER</span><span>A good spirit to have around.</span><Solana/></div></footer>
 </main></div>
 <Dialog open={notice!==null} onOpenChange={open=>{if(!open)setNotice(null);}}><DialogContent className="cashper-dialog"><Mascot decorative /><span className="eyebrow">COMING SOON</span><DialogTitle className="dialog-title">{notice}</DialogTitle><DialogDescription className="dialog-description">The official link has not been announced yet. Check back here for updates.</DialogDescription><button className="button dialog-button" onClick={()=>{setNotice(null);document.getElementById('tools')?.scrollIntoView({behavior:'smooth'});}}>Explore Ghost Tools <ArrowRight size={18} /></button></DialogContent></Dialog><SearchSheet panel={panel} onOpenChange={open=>{if(!open)setPanel(null);}} /></>;
}
